version: '3.5'

services:
  attachment:
    container_name: attachment
    build:
      context: .
    ports:
      - "8070:8070"
    networks:
      - auth-service_social_media_network  # Use the same network as auth
    restart: unless-stopped
    env_file:
      - base.env
   

networks:
  auth-service_social_media_network:
    external:
      name: auth-service_social_media_network  # Define the network as external

